######################################################################
# Automatically generated by qmake (2.01a) Thu Jul 1 11:15:23 2010
######################################################################

TEMPLATE = app
QT += core dbus
QT -= gui
CONFIG += debug link_pkgconfig console
CONFIG -= gui
PKGCONFIG += libsocialweb-qt

# Directories

HEADERS += \
#    ../../repos/m2/libsocialweb-qt/*.h \
#    ../../repos/m2/libsocialweb-qt/interfaces/*.h \
    swclientapp.h

SOURCES += \
#    ../../repos/m2/libsocialweb-qt/*.cpp \
#    ../../repos/m2/libsocialweb-qt/interfaces/*.cpp \
    swclientapp.cpp \
    main.cpp
#INCLUDEPATH += ../../repos/m2/libsocialweb-qt \
#    /usr/include/glib-2.0 \
#    /usr/include/gconf/2
#LIBS += -L../../repos/m2/libsocialweb-qt -lsocialweb-qt
